### ISSUE TITLE
Node not uploading data

### ISSUE THREAD

**Issue by SentientCrab** [beakerbrowser/dat-node#9]
Been having a problem with dat-node seeding the site. Here's what I'm doing

1. Create a site on computer a.
2. Run this script.
```const {createNode} = require('@beaker/dat-node')

// instantiate a new dat node
const dat = createNode({
  path: './dat',
autoSwarm: true,
autoListen: true
})

async function a()
{
var archive = await dat.getArchive(DAT_CREATED_ON_COMPUTER_A)
var filedata  = await archive.readFile('/index.html', 'utf8')
console.log(filedata)
}

a()
```
3. Close out of computer a.
4. Open the dat on computer b.

Every time computer b fails to connect to the site. Adding listeners to the script shows that it sees the new connection, but for some reason no data is transferred. Sometimes I can see the peer in beaker's swarm debugger but I think the handshake gets timed out. I forgot to take a screenshot so I'm not sure. Using dat.createArchive works fine, and I've experimented not using await on dat.getArchive, doing join swarm instead of dat.getArchive, joining the swarm before getting the archive, etc.

**Comment by pfrazee** [comment]
Try modifying your script to download all files in the archive prior to closing computer a. It's possible that Beaker is failing to load the site because it can't access the `dat.json` manifest file.

**Comment by SentientCrab** [comment]
Oh wow I feel dumb. I thought getting the archive was downloading it. That fixed the problem.

**Comment by pfrazee** [comment]
No worries!
